### ISSUE TITLE
Fails on `subdirs` of location.

### ISSUE THREAD

**Issue by Fuuzetsu** [typeable/stackage2nix#30]
I have a repository with multiple packages in it (mega repo). I want to use packages from it. In stack this is expressible by

```
- location:
    git: giturl
    commit: gitrev
  subdirs:
    - package1
    - package2
```

https://docs.haskellstack.org/en/stable/yaml_configuration/#complex-package-locations-location

However on such a setup, stackage2nix fails through cabal2nix:

`*** found zero or more than one cabal file ([]). Exiting.`
